apiVersion: v1
kind: Pod
metadata:
  name: fiap-multi-container

spec:
  containers:
    - name: nginx-container-1
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /data   
  volumes:
    - name: shared-data
      hostPath:
        path: /run/desktop/mnt/host/c/FIAP/Aulas/02-microsservicos-e-orquestracao-de-containers/02-kubernetes/aula-06/topic-01/exemplo_2/data
        type: Directory
